### ISSUE TITLE
Issue in originatesFrom.tsx

### ISSUE THREAD

**Issue by MadCatX** [Molecular-Biophysics-Database/mbdb-input-ui#85]
1) The name of the file does not conform to the convention used by the project. The name should be `originates-from.tsx`. It is advisable to not mix letter case in file names because file names `Abc.Txt` vs .`abc.txt` may be considered equal on some platforms.

2) The
```jsx
<>
    <SDropdown ...>
    </SDropdown>
</>
```
block can be replaced with
```jsx
<SDropdown ...
 />
```

**Comment by TereziePrchalova** [comment]
Fixed
