### ISSUE TITLE
Label of file component is floating next to the form

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-input-ui#92]
the Bug occurs in In the field metadata.general_parameters.instrument.performance_test.report 

![image](https://github.com/Molecular-Biophysics-Database/mbdb-input-ui/assets/20229814/4bbcfe1e-cdd2-4534-9792-0f07952684b6)

**Comment by MadCatX** [comment]
Related PR https://github.com/Molecular-Biophysics-Database/mbdb-input-ui/pull/93
